spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5417/dbwebflux
    username: webflux
    password: webflux

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'false'
  docker:
    compose:
      enabled: true
