spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5417/dbwebflux
    username: webflux
    password: webflux

  docker:
    compose:
      enabled: true
logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG # for queries
    io.r2dbc.postgresql.PARAM: DEBUG # for parameters